### ISSUE TITLE
Sorry for the question issue - feel free to close...

### ISSUE THREAD

**Issue by HeneryH** [Vardot/varbase_story_demo#9]
How is this different than just creating a default 'story' content type that lets you free edit the story with embedded media?

What problem are you trying to solve with this?

**Comment by Natshah** [comment]
Not prob.
**It's a Demo**
It' helps in demoing and testing each media type for  field_image, field_video, field_media.
with limitation of 1, 2, 3 or unlimited
using Entity Browser or Media Library
